# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
timezone: Europe/London

# Site settings
title: -1/+2 - One Down Two Up
url: "http://onedowntwoup.com"
description: >
    I'm writing about my journey from novice trackway goer to racer. 
    Offering hints and tips on the way as I try to figure out this business of going fast.
email: hello@onedowntwoup.com
twitter_username: _onedowntwoup
facebook_username: onedowntwoup
instagram_username: onedowntwoup
